/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package stumanage;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import stumanage.jingjing.dao.DaoImpl;
import stumanage.jingjing.util.Center;

/**
 *
 * @author Administrator
 */
public class Basic extends javax.swing.JFrame {

    /**
     * Creates new form Basic
     */
    public Basic(String username) {
        
        initComponents(); 
        this.getContentPane().setBackground(new Color(95,158,160));  
        this.getContentPane().setVisible(true);//如果改为true那么就变成了红色。  
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); 
        Center.setCenter(this);
        this.setVisible(true);
        this.Tnumber.setText(username);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Tnumber = new javax.swing.JTextField();
        Tname = new javax.swing.JTextField();
        Tage = new javax.swing.JTextField();
        Tsex = new javax.swing.JTextField();
        Tcall = new javax.swing.JTextField();
        Temail = new javax.swing.JTextField();
        Tadd = new javax.swing.JTextField();
        Tclass = new javax.swing.JTextField();
        Enumber = new javax.swing.JLabel();
        Ename = new javax.swing.JLabel();
        Eage = new javax.swing.JLabel();
        Esex = new javax.swing.JLabel();
        Ecall = new javax.swing.JLabel();
        Eemail = new javax.swing.JLabel();
        Eadd = new javax.swing.JLabel();
        Eclass = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("惊天科技--->完善...");

        jLabel1.setForeground(new java.awt.Color(62, 56, 56));
        jLabel1.setText("------------------完善注册-----------------");

        jLabel2.setForeground(new java.awt.Color(62, 56, 56));
        jLabel2.setText("学号：");

        jLabel3.setForeground(new java.awt.Color(62, 56, 56));
        jLabel3.setText("姓名：");

        jLabel4.setForeground(new java.awt.Color(62, 56, 56));
        jLabel4.setText("年龄：");

        jLabel5.setForeground(new java.awt.Color(62, 56, 56));
        jLabel5.setText("性别：");

        jLabel6.setForeground(new java.awt.Color(62, 56, 56));
        jLabel6.setText("手机：");

        jLabel7.setForeground(new java.awt.Color(62, 56, 56));
        jLabel7.setText("QQ邮箱：");

        jLabel8.setForeground(new java.awt.Color(62, 56, 56));
        jLabel8.setText("住址：");

        jLabel9.setForeground(new java.awt.Color(62, 56, 56));
        jLabel9.setText("班号：");

        Tnumber.setEditable(false);
        Tnumber.setForeground(new java.awt.Color(62, 56, 56));

        Tname.setForeground(new java.awt.Color(62, 56, 56));
        Tname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TnameActionPerformed(evt);
            }
        });
        Tname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TnameFocusLost(evt);
            }
        });

        Tage.setForeground(new java.awt.Color(62, 56, 56));
        Tage.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TageFocusLost(evt);
            }
        });

        Tsex.setForeground(new java.awt.Color(62, 56, 56));
        Tsex.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TsexFocusLost(evt);
            }
        });

        Tcall.setForeground(new java.awt.Color(62, 56, 56));
        Tcall.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TcallFocusLost(evt);
            }
        });

        Temail.setForeground(new java.awt.Color(62, 56, 56));
        Temail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TemailFocusLost(evt);
            }
        });

        Tadd.setForeground(new java.awt.Color(62, 56, 56));
        Tadd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TaddFocusLost(evt);
            }
        });

        Tclass.setForeground(new java.awt.Color(62, 56, 56));
        Tclass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TclassActionPerformed(evt);
            }
        });
        Tclass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TclassFocusLost(evt);
            }
        });

        jButton2.setForeground(new java.awt.Color(62, 56, 56));
        jButton2.setText("提交");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setForeground(new java.awt.Color(62, 56, 56));
        jButton3.setText("直接退出");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setForeground(new java.awt.Color(62, 56, 56));
        jButton4.setText("重置");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 255));
        jLabel10.setText("-----惊天科技--------------------");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(jLabel2))
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Tclass, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                    .addComponent(Tadd)
                                    .addComponent(Temail)
                                    .addComponent(Tcall)
                                    .addComponent(Tsex)
                                    .addComponent(Tname, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Tnumber, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Tage)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4)
                                .addGap(22, 22, 22)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(Eage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Esex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Ecall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Eemail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Eadd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Eclass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Ename, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Enumber, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(13, 13, 13))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 64, Short.MAX_VALUE))
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel10)
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Tnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Enumber))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Tname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ename))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Tage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Eage))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Tsex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Esex))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Tcall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ecall))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Temail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Eemail))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Tadd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Eadd))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(Tclass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Eclass))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton4)
                    .addComponent(jButton3))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if(submit()){
            this.dispose();
            UsualUser uu=new UsualUser(Tnumber.getText());
        }else{
            JOptionPane.showMessageDialog(jButton2,"插入失败");
            reset();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TnameActionPerformed
    private boolean submit(){
        if(Enumber.getText()!=""||Ename.getText()!=""||Eage.getText()!=""||Esex.getText()!=""||Ecall.getText()!=""||Eemail.getText()!=""||Eadd.getText()!=""){
            JOptionPane.showMessageDialog(jButton2,"内容格式有误");
            return false;
        }else{
            int num=Integer.parseInt(Tclass.getText());
            int age=Integer.parseInt(Tage.getText());
            int sex=0;
            if(Tsex.getText().equals("男")){
                sex=1;
            }
            DaoImpl dao=new DaoImpl();
            if(dao.insertBasic(Tnumber.getText(), Tname.getText(), age, sex, Tcall.getText(), Temail.getText(), Tadd.getText())){
                if(dao.insertConnection(Tnumber.getText(), num)){
                    return true; 
                }else{
                    return false;
                }
            }else{
                return false;
            }
         }
        }
            
        
    private void TnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TnameFocusLost
        if(!Tname.getText().matches("[\\u4E00-\\u9FA5]{2,5}")){
            Ename.setText("输入2-5个汉字");
            Tname.setText("");
        }else{
            Ename.setText("");
        }
    }//GEN-LAST:event_TnameFocusLost

    private void TageFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TageFocusLost
        if(!Tage.getText().matches("[1-9]{1}[0-9]{1}")){
            Eage.setText("年龄在10-99之间");
            Tage.setText("");
        }else{
            Eage.setText("");
        }
    }//GEN-LAST:event_TageFocusLost

    private void TsexFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TsexFocusLost
        if(!Tsex.getText().matches("男||女")){
            Esex.setText("性别只能为男女");
            Tsex.setText("");
        }else{
            Esex.setText("");
        }
    }//GEN-LAST:event_TsexFocusLost

    private void TcallFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TcallFocusLost
        if(!Tcall.getText().matches("1[3,4,5,7,8]{1}[0-9]{9}")){
            Ecall.setText("手机号不正确");
            Tcall.setText("");
        }else{
            Ecall.setText("");
        }
    }//GEN-LAST:event_TcallFocusLost

    private void TemailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TemailFocusLost
        //邮箱
        if(!Temail.getText().matches("[1-9][0-9]{6,11}@[q,Q][q,Q].com")){
            Eemail.setText("qq邮箱格式不正确");
            Temail.setText("");
        }else{
            Eemail.setText("");
        }
    }//GEN-LAST:event_TemailFocusLost

    private void TaddFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TaddFocusLost
        if(!Tadd.getText().matches("[\\u4E00-\\u9FA5]{6,20}")){
            Eadd.setText("请输入正确地址");
            Tadd.setText("");
        }else{
            Eadd.setText("");
        }
    }//GEN-LAST:event_TaddFocusLost

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        reset();
    }//GEN-LAST:event_jButton4ActionPerformed
    private void reset(){
        Tname.setText("");
        Ename.setText("");
        Tage.setText("");
        Eage.setText("");
        Tsex.setText("");
        Esex.setText("");
        Tcall.setText("");
        Ecall.setText("");
        Temail.setText("");
        Eemail.setText("");
        Tadd.setText("");
        Eadd.setText("");
        Tclass.setText("");
        Eclass.setText("");
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void TclassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TclassFocusLost
        if(!Tclass.getText().matches("[1-6]{1}")){
            Eclass.setText("班号输入有误");
            Tclass.setText("");
        }else{
            Eclass.setText("");
        }
    }//GEN-LAST:event_TclassFocusLost

    private void TclassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TclassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TclassActionPerformed

//    public static void main(String args[]) {
//       
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Basic("20000000001").setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Eadd;
    private javax.swing.JLabel Eage;
    private javax.swing.JLabel Ecall;
    private javax.swing.JLabel Eclass;
    private javax.swing.JLabel Eemail;
    private javax.swing.JLabel Ename;
    private javax.swing.JLabel Enumber;
    private javax.swing.JLabel Esex;
    private javax.swing.JTextField Tadd;
    private javax.swing.JTextField Tage;
    private javax.swing.JTextField Tcall;
    private javax.swing.JTextField Tclass;
    private javax.swing.JTextField Temail;
    private javax.swing.JTextField Tname;
    private javax.swing.JTextField Tnumber;
    private javax.swing.JTextField Tsex;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
